services:
  # main: # IDE runs in this container
  #   working_dir: /workspace
  #   build:
  #     context: .
  #     dockerfile: Dockerfile

  #   volumes:
  #   # Update this to wherever you want VS Code to mount the folder for your project
  #   - .:/workspace

  #   # Overrides default command so things don't shut down after the process ends.
  #   command: /bin/sh -c "while sleep 1000; do :; done"

  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=artifactory
      - POSTGRES_USER=artifactory
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U artifactory"]
      interval: 10s
      timeout: 5s
      retries: 5

  artifactory:
    image: ${DOCKER_REGISTRY}/jfrog/artifactory-pro:${ARTIFACTORY_VERSION}
    container_name: artifactory
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - HL_CLIENT_ID=${HL_CLIENT_ID}
      - HL_CLIENT_SECRET=${HL_CLIENT_SECRET}
      - HL_API_URL=${HL_API_URL}
      - JF_ROUTER_ENTRYPOINTS_EXTERNALPORT=${JF_ROUTER_ENTRYPOINTS_EXTERNALPORT}
      - JF_SHARED_DATABASE_TYPE=postgresql
      - JF_SHARED_DATABASE_DRIVER=org.postgresql.Driver
      - JF_SHARED_DATABASE_URL=jdbc:postgresql://postgres:5432/artifactory
      - JF_SHARED_DATABASE_USERNAME=artifactory
      - JF_SHARED_DATABASE_PASSWORD=password
      - JF_SHARED_SECURITY_MASTERKEY=ca5902baf7794f57037a55ec893ae7b6
      - JF_SHARED_SECURITY_JOINKEY=fa83de614cbc1ced190dc29e61d895bf
    ports:
      - 8081:8081 # /artifactory API
      - ${JF_ROUTER_ENTRYPOINTS_EXTERNALPORT}:${JF_ROUTER_ENTRYPOINTS_EXTERNALPORT} # UI
    volumes:
      - ./core/src:/opt/jfrog/artifactory/var/etc/artifactory/plugins
      - ./build/deps:/opt/jfrog/artifactory/var/etc/artifactory/plugins/lib
      - artifactory:/var/opt/jfrog/artifactory
      - ./config/artifactory.system.properties:/opt/jfrog/artifactory/var/etc/artifactory/artifactory.system.properties
      - ./config/access.config.patch.yml:/opt/jfrog/artifactory/var/etc/access/access.config.patch.yml
      - ./config/logback.xml:/opt/jfrog/artifactory/var/etc/artifactory/logback.xml
      - /etc/localtime:/etc/localtime:ro
    networks:
      - default
    ulimits:
      nproc: 65535
      nofile:
        soft: 32000
        hard: 40000

volumes:
  postgres-data:
  artifactory:

networks:
  default:
    name: custom_network
