version: "3.7"

services:
  # main: # IDE runs in this container
  #   working_dir: /workspace
  #   build:
  #     context: .
  #     dockerfile: Dockerfile

  #   volumes:
  #   # Update this to wherever you want VS Code to mount the folder for your project
  #   - .:/workspace

  #   # Overrides default command so things don't shut down after the process ends.
  #   command: /bin/sh -c "while sleep 1000; do :; done"

  artifactory:
    image: ${DOCKER_REGISTRY}/jfrog/artifactory-pro:${ARTIFACTORY_VERSION}
    container_name: artifactory
    environment:
      - JF_ROUTER_ENTRYPOINTS_EXTERNALPORT=${JF_ROUTER_ENTRYPOINTS_EXTERNALPORT}
      - JAVA_OPTS="-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
    ports:
      - 8081:8081 # /artifactory API
      - ${JF_ROUTER_ENTRYPOINTS_EXTERNALPORT}:${JF_ROUTER_ENTRYPOINTS_EXTERNALPORT} # UI
      - 5005:5005 # Debug port
    volumes:
      - ./core/src:/opt/jfrog/artifactory/var/etc/artifactory/plugins
      - artifactory:/var/opt/jfrog/artifactory
      - ./config/artifactory.system.properties:/opt/jfrog/artifactory/var/etc/artifactory/artifactory.system.properties
      - ./config/logback.xml:/opt/jfrog/artifactory/var/etc/artifactory/logback.xml
      - /etc/localtime:/etc/localtime:ro
    ulimits:
      nproc: 65535
      nofile:
        soft: 32000
        hard: 40000

volumes:
  artifactory:
