name: Plugin CI

on:
    pull_request: {}
    push:
      branches:
        - main

permissions:
    contents: read

jobs:
    test:
        name: Test plugin
        runs-on: ubuntu-latest
        env:
            HL_CLIENT_ID: ${{ vars.HL_CLIENT_ID }}
            HL_CLIENT_SECRET: ${{ secrets.HL_CLIENT_SECRET }}
            RT_LICENSE_KEY: ${{ secrets.RT_LICENSE_KEY }}
        steps:
            - name: Harden Runner
              uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
              with:
                egress-policy: audit

            - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
            - name: Setup Java
              uses: actions/setup-java@3a4f6e1af504cf6a31855fa899c6aa5355ba6c12 # v4.7.0
              with:
                java-version: '11'
                distribution: 'temurin'
            - name: Setup Gradle
              uses: gradle/actions/setup-gradle@4d9f0ba0025fe599b4ebab900eb7f3a1d93ef4c2 # v5.0.0
              with:
                gradle-version: '8.8'
            - name: Grant write permission to plugins directory
              # The artifactory service needs to be able to write to the plugins folder
              run: chmod a+rwx -R core/src
            - name: Copy dependencies
              run: gradle copy_deps
            - name: Start containers
              run: docker compose up -d
            - name: Setup tests
              run: gradle artifactory_common
            - name: Run plugin tests
              run: gradle modelscanner
            - name: Stop containers
              if: always()
              run: docker compose down
